### ISSUE TITLE
Dates back until 10.000 BC (-10.000)

### ISSUE THREAD

**Issue by bsnizek** [anitagraser/TimeManager#155]
Hey,

 what needs to be done so TM works with years down to 10.000 BC  ? 

Cheers

 /B

**Comment by carolinux** [comment]
I am assuming you have gotten as far in the user interface so as to enable archaelogical mode by clicking on the small acropolis. Then you are shown this message: 

> You are trying to activate Time Manager Archaeological mode.
> 
>  By doing so, regular datetimes won't work, and the program will expect values of the format  0003 BC or 0012 AD (if the number of digits is set to 4).
> Year 0 doesn't exist, replace it with either 0001 BC or 0001 AD
> 
> You can vary the number of digits below if you require more for your project. All years in all layers need to have the same number of digits, even if that means adding extra zeroes in the front.

So you need to set the number of digits to **5** (instead of the default 4) and have your dataset be like
00010 BC
01001 AD
with the zeroes exactly as written.  If you have problems, you can attach your dataset here and I can tell you if something is wrong with the dataformat.

**Comment by bsnizek** [comment]
Thanx for your quick answer. We did not see the Akropolis. Works now !
Great !!!!!

/B

**Comment by carolinux** [comment]
Excellent :-)
