### ISSUE TITLE
Error while attempting to export a video

### ISSUE THREAD

**Issue by pcav** [anitagraser/TimeManager#160]
I get this, and no video. Thanks.

===
CalledProcessError: Command '['convert', '-delay', '1x10',
u'/home/paolo/Documents/Lavori/cfs/time_itri/animation.gif']' returned
non-zero exit status 1
Traceback (most recent call last):
  File
"/home/paolo/.qgis2/python/plugins/timemanager/timemanagercontrol.py",
line 266, in exportVideo
    animate.make_animation(path, delay_millis)
  File
"/home/paolo/.qgis2/python/plugins/timemanager/animation/animate.py",
line 42, in make_animation
    ret = subprocess.check_call(args)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['convert', '-delay', '1x10',
u'/home/paolo/Documents/Lavori/cfs/time_itri/animation.gif']' returned
non-zero exit status 1

**Comment by carolinux** [comment]
What files does the directory:
/home/paolo/Documents/Lavori/cfs/time_itri/

have?

**Comment by pcav** [comment]
Empty

**Comment by carolinux** [comment]
ok then no frames are being exported, please scroll all the way to the beginning of the timeline, and then try.

**Comment by pcav** [comment]
Right, now it works. Unclear why the error however.
Thanks.

**Comment by carolinux** [comment]
I think what must have happened is that you clicked export when the timeline was at the end, so it didnt export any frames, and then the imagemagick command failed. I added a better error for this case.

**Comment by Namkolla** [comment]
I was having the same issue trying to use the ffmpeg option for downloading a video. I think it was because I was not letting the process finish. 

After you hit "Export Video" and fill out the settings, you get prompted with "Image sequence from current position onwards is being saved to [path]. Please wait until the process is finished" there is a misleading option to click "Ok". I didn't click "Ok" and sure enough the frames started appearing in the correct folder. You can also check that it's working by looking at the Browser window (in QGIS) and the png files will start appearing.
