### ISSUE TITLE
Export video skips frames

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#197]
I think the current version 2.3 has an issue with skipping frames when exporting image series / videos.

**Comment by anitagraser** [comment]
This issue did not exist in 2.2.4. Could it be cause by changes to QTimer?

**Comment by carolinux** [comment]
That could be, otherwise not much was changed wrt this functionality.
Try reverting the relevant commit 26daa7a74f8533864ae3f91e942 
ie 
```git revert 26daa7a74f8533864ae3f91e942``` 
in your machine

**Comment by rduivenvoorde** [comment]
@anitagraser @carolinux mmm, could be a problem with the QTimer, how did you test?
Would be nice if we could add a test for this: export 20 frames and count if we really get those..

The way it now works is (if I'm correct) that the starting of a new timer, stops the timer if it was already running. Which in normal cases is what you want, because you do not want the old processes retrieving (stale) data. For example for a wms-t layer, it firing requests when you dragged the slider.

But even in the export case, you should only start a new frame when the earlier one is finished exporting.

If you provide me some test data (or point me to an excisting set from the current test data which fails..), I can try to add a test, and test both setups

**Comment by anitagraser** [comment]
Thanks for your feedback! The issue appeared at work, so I still need to look for a dataset that can be shared that shows the problem - probably the Geolife example from the Time Manager workshops material.

**Comment by carolinux** [comment]
The thing is there is already a test on the number of frames generated in the export which passes:
https://github.com/anitagraser/TimeManager/blob/master/test/test_functionality.py#L287

Export mode doesn't use QTimer, so this is further indication that this is where the problem lies.

**Comment by rduivenvoorde** [comment]
@carolinux you mean: that the QTimer change IS the problem, or is NOT the problem  for Anita's exporting problem?

One thing I see is that because we do:
self.iface.mapCanvas().mapCanvasRefreshed.connect(self.waitAfterRenderComplete)
we will always create and start the timer as soon as there is some canvas refresh (even without doing anything with the plugin)?

**Comment by carolinux** [comment]
that the QTimer change is the problem

**Comment by rduivenvoorde** [comment]
Thanks for the quick reply.

One thing I can think of is that the fact that the 'playing of a timerange' is connected to the mapCanvasRefreshed-signal,  that it ( a nextstep) is called maybe too often? Before the Qtimer change I had too many frames sometimes: the canvas refreshed because of the late arrival of webservices, and started a new 'step' again..

Now WITH the Qtimer change, I still have the feeling that we should not count on the mapCanvasRefreshed-signal because the canvas can be updated outside of the timemanager context too... And (if I understand correct), the mapCanvasRefreshed-signal is actually always triggering a next step.

A problem I personally have for example: having a rather large dataset with labels defined. Because the rendering of the labels takes so much time, the QTimer is running too fast: a renderingstep is not yet finished and the next step is already fired (thereby skipping that slow frame).

(I'm not sure why the earlier setup did not have that problem though)

There is a clear distinction between the behavior needed when you step by hand or in 'play' modus. 
When you step by hand, you want a quick 'next step' to invalidate/overwrite the earlier step: 'loosing' a frame is ok in that modus.
On the other hand when you 'play' (or export) you will NEVER want to loose a frame. So a call for a next step BEFORE the former step is truly finished should hold back until we are sure the step before is 100% ready... I'm not sure if you can check that though, I do not think there is a 100% clear signal when all layers are 100% rendered... Or we should create some semaphore/lock for our part of the rendering?

Am I clear enough?

But best if we have at least a good 'problem' dataset and configuration so we can do the right testing.

**Comment by carolinux** [comment]
@anitagraser: Use the fixes branch where I revert the QTimer commit, just in case this changes the behavior and let me know please.

**Comment by anitagraser** [comment]
The issue can be reproduced with this test dataset https://drive.google.com/file/d/0Bwc-5JFVTnfIX29iX2xydVFPRVU/view?usp=sharing (spatialite + project)

I'll try with the branch next

**Comment by anitagraser** [comment]
@carolinux your fix solved the issue

**Comment by carolinux** [comment]
@anitagraser OK, I say let's do a release with that? Seems more people are having export problems.

**Comment by anitagraser** [comment]
@carolinux Ok. Will you merge the fixes branch into master?

**Comment by carolinux** [comment]
yep and I can do a new release on Mon

**Comment by anitagraser** [comment]
Ok thank you! I've unapproved the problematic 2.3 version on plugins.qgis.org now.

**Comment by carolinux** [comment]
@anitagraser seems like I don't have permission to approve a new version on qgis.org although I uploaded it.. maybe you can? (2.3.1)

Also, 2.3 is still listed as approved.

**Comment by carolinux** [comment]
fixed in 2.3.1 which is now live on the plugins.qgis.org
