### ISSUE TITLE
Add support for raster layers

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#21]
The timestamp should be encoded in the file or layer name.

**Comment by carolinux** [comment]
I will check how raster support works now

**Comment by anitagraser** [comment]
In the current release version, the user can add raster layers, but it seems like all input is ignored and after reopening the settings dialog, all raster layer settings have disappeared.

**Comment by carolinux** [comment]
yeah, haven't had time to check this. Probably there is a log message if you see the logs (in the TimeManager tab). Please tell me what it is if there is one.

**Comment by carolinux** [comment]
try this fix <:o)
also now I understand how raster layers are used..

**Comment by anitagraser** [comment]
Thanks, the settings are stored now. Now, it just seems like the layers are not managed as they should be: all raster layers are displayed irregardless of the configured time.

**Comment by carolinux** [comment]
The issue was that the layers were not being repainted after the opacity had changed - iface.mapCanvas().refresh() somehow doesn't refresh raster layers, but it does refresh the vector layers with a changed subset string.

 I am not sure how it worked before, maybe the refresh behavior is a recent change in qgis.core, but now to repaint one needs to do layer.triggerRepaint(). I see there's a lot of potential for improvement. Do you think that for starters, users should be able to define a start/end in the filename to extract the timestamp from? ( #57 is related also)

**Comment by anitagraser** [comment]
It would certainly improve usability if Time Manager could parse times from the file/layer names.

**Comment by carolinux** [comment]
Yeah, please do.

**Comment by anitagraser** [comment]
done

**Comment by carolinux** [comment]
closing this to make more specific ones
