### ISSUE TITLE
Time Manager shows features one frame before it should

### ISSUE THREAD

**Issue by CoryAlbrecht** [anitagraser/TimeManager#235]
I found this out trying to make my first animation with Time Manager. When walking through a time line one frame at a time, features are shown in the frame before they should be.

Take these three frames attached below made with the "Export Video' button.

That light pink area is only two features. The second frame is the two overlapping, not a third feature. Time Manager is configured to use the fields "start_time" and "end_time" which is formatted as "YYYY-mm-dd" and set to advance 1 day at a time.  The first feature has those fields set to "1670-05-02" and "1819-01-29", the second feature is set to "1819-01-30" and "1870-07-15".

But the second feature appears, as you can see, when the timeline reaches 1819-01-29, not the 30th.

That leads to that second frame happening where the two features overlap.

If I change the stepping to 1 hour, feature two then appears at 1819-01-20 23:00:00 which is the frame before 1819-01-30 00:00:00 when one would expect it to appear. Appearing a frame too early appears to happen for every object and regardless of the stepping.

![image](https://user-images.githubusercontent.com/8172909/29440880-2cbf733e-8396-11e7-8ecd-3567b53ccde4.png)

![image](https://user-images.githubusercontent.com/8172909/29440885-372d980a-8396-11e7-96a1-70d3d3b326d5.png)

![image](https://user-images.githubusercontent.com/8172909/29440888-3d376050-8396-11e7-9dea-a7b5b99f8b28.png)

![image](https://user-images.githubusercontent.com/8172909/29441052-9e282552-8396-11e7-82f2-ac28c4390b99.png)

![image](https://user-images.githubusercontent.com/8172909/29441337-9f154290-8398-11e7-90c7-759046285c64.png)

**Comment by CoryAlbrecht** [comment]
Is this QGIS plugin project moribund? I don't see many updates other than people reporting problems or requesting features.

**Comment by anitagraser** [comment]
I'm fixing issues as I encounter them but nobody is paid to maintain this plugin. Note that it is easier to look into issues that provide test data.

The effect you observe is caused by the filter query being set to: 

`cast("t1" as character) <= '1819/01/30' AND cast("t2" as character) >= '1819/01/29' `

while you expect 

`cast("t1" as character) < '1819/01/30' AND cast("t2" as character) >= '1819/01/29' `

This is caused by an explicit check in query_builder.py:

`comparison = "<" if to_attr == from_attr else "<="`

I'm sure there was a reason ... @carolinux ?

In the meantime, you can edit your copy of query_builder.py to get the behavior you expect.

**Comment by CoryAlbrecht** [comment]
I understand the vicissitudes of maintaining open source software, but it is nice to get an acknowledgement  of the problem even if triage gives it a lower priority.

Thank you for figuring out a kludge for me to apply until the issue has been dealt with.
