### ISSUE TITLE
Millisecond and microsecond support is buggy

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#48]
The subset query string does not correctly reflect milliseconds or microseconds. The precision is always limited to seconds.

**Comment by zebitz** [comment]
I understand that TimeManager has currently no support for time steps below one second due to dependencies on underlying libraries. 
I am currently playing with a georeferenced tracking data set obtained from computer vision tracking of pedestrians with a frame rate of 30 fps where the pedestrians are represented as moving points (ID, x, y, t). I also have corresponding manually annotated ground truth data as well, and I thus need to compare and visualize the two data sets preferably frame by frame in the same movie. I had hoped that TimeManager could do this for me, but to do so correctly I would need milliseconds support. Right now I set the time period to one second which renders 30 points pr. track for each frame generated in TimeManager, but it is not as elegant a solution as I dreamed of. The puzzling thing with my data is that one of the data sets seems to render correctly with a time step period set to 100 microseconds - there it renders 3 track points pr. time step as expected, whereas the other data set with the same setup display all 30 track points at the 900'th microsecond mark for each second - and this even though the two data sets have similar columns in the PostGIS database I load them from (see pics).

Would it by any means be possible that the milliseconds bug can be fixed in future versions?

![800milli](https://cloud.githubusercontent.com/assets/7261601/6331447/6bca4568-bb7f-11e4-96c8-c63786fcd62f.png)
![900milli](https://cloud.githubusercontent.com/assets/7261601/6331448/6bd22b5c-bb7f-11e4-9773-3b1f161f5193.png)

**Comment by carolinux** [comment]
Improved handling of timesteps (microseconds, centuries) is something several people ask about, so it is quite high on the list for new features when I get time to work on them.

**Comment by zebitz** [comment]
Sounds very good. I'll get back to you on gmail regarding the data.

**Comment by carolinux** [comment]
I thought about it a bit, I have an idea what may be causing it. Could it be that the only difference between those two datasets is that one always use the same number of digits for the fractional seconds (padding with zero when necessary) and the other doesn't? At any case, I think it shouldnt be that hard to fix.

**Comment by zebitz** [comment]
They are both padded with zeros to fill all six digits for micro seconds. Considered if that could be a problem to begin with, but that was not it.

**Comment by carolinux** [comment]
UPDATE: The issue was indeed something to do with missing zeroes, although not exactly what I had in mind. It seems the microsecond and millisecond support works well when the data can be detected by timemanager to be of the format YYYMMMDD HHMMSS.f but this is not always the case due to databases not representing trailing zeroes in their date formats. Another related thing is that if we have timestamps that are floats (ie integer timestamp with milliseconds after the dot) this isn't supported either, but so far nobody has asked for this.

**Comment by zebitz** [comment]
Yes it turned out to be a trailing zeros issue, since the trailing zeros were cut off in PostGIS, even though it was made sure all 6 digits to represent microseconds were there in the text file that was loaded into PostGIS. 
The solutions was in PostGIS to cast the datetime field to a string in a new field and force this string representation to display all trailing zeros. Then the string representation can be used as the timestamp as the starttime in QGIS TimeManager.
 
In the create table statement define: 
        dt timestamp without time zone,
	dtstr text, 

Afterwards in an UPDATE table statement:
        SET dtstr = to_char(dt, 'YYYY-MM-DD HH24:MI:SS.US'); 

Then in QGIS TimeManager use dtstr as Starttime.

Thank you so much for a quick solution. TimeManager rocks;-)

**Comment by carolinux** [comment]
ammended microsecond support also
